"""Parse, aggregate, and route scope-deltas from deep scan feedback.

Translates the post-scan feedback collection and routing from scan.sh.
"""

from __future__ import annotations
from pathlib import Path

from signals.repository.artifact_io import read_json, write_json
from orchestrator.path_registry import PathRegistry
from scan.service.feedback_router import (
    _append_to_log,
    _extract_section_number,
    _is_valid_updater_signal,
    _route_scope_deltas,
    _validate_feedback_schema,
)
from scan.related.discovery import apply_related_files_update
from scan.service.template_loader import load_scan_template

from dispatch.service.prompt_guard import validate_dynamic_content

from scan.cli_dispatch import dispatch_agent, read_scan_model_policy
from taskrouter import agent_for


def collect_and_route_feedback(
    *,
    section_files: list[Path],
    codemap_path: Path,
    codespace: Path,
    artifacts_dir: Path,
    scan_log_dir: Path,
    model_policy: dict[str, str] | None = None,
) -> bool:
    """Collect feedback from deep scan, produce report, and route findings.

    Returns ``True`` if any feedback was found.
    """
    if model_policy is None:
        model_policy = read_scan_model_policy(artifacts_dir)
    print("--- Deep Scan: collecting feedback ---")

    feedback_report = artifacts_dir / "scan-feedback.md"
    report_lines = [
        "# Scan Feedback Report\n",
        "\nGenerated by deep scan. Review and apply if needed.\n\n",
    ]

    has_feedback = False

    for section_file in section_files:
        sec_name = section_file.stem
        sec_log_dir = scan_log_dir / sec_name

        irrelevant_files: list[str] = []
        missing_files: list[str] = []
        out_of_scope_items: list[str] = []

        for fb_file in sorted(sec_log_dir.glob("deep-*-feedback.json")):
            data = read_json(fb_file)
            if data is None:
                print(
                    f"[DEEP SCAN] WARNING: Malformed feedback JSON: "
                    f"{fb_file} (section: {sec_name})",
                )
                _append_to_log(
                    scan_log_dir / "failures.log",
                    f"- Malformed feedback: `{fb_file}` (section: {sec_name})",
                )
                continue

            # Schema validation: required fields must be present and typed
            if not _validate_feedback_schema(data, fb_file, sec_name, scan_log_dir):
                continue

            relevant = data["relevant"]
            if relevant is False:
                reason = data.get("reason", "")
                src_path = data["source_file"]
                irrelevant_files.append(f"- {src_path}: {reason}")
                has_feedback = True

            # Collect missing files
            for mf in data.get("missing_files", []):
                if isinstance(mf, str) and mf.strip():
                    missing_files.append(f"- {mf.strip()}")
                    has_feedback = True

            # Collect out-of-scope
            for oos in data.get("out_of_scope", []):
                if isinstance(oos, str) and oos.strip():
                    out_of_scope_items.append(f"- {oos.strip()}")
                    has_feedback = True

        if irrelevant_files or missing_files or out_of_scope_items:
            report_lines.append(f"## {sec_name}\n\n")
            if irrelevant_files:
                report_lines.append(
                    "### Irrelevant files (consider removing)\n",
                )
                report_lines.extend(f"{line}\n" for line in irrelevant_files)
                report_lines.append("\n")
            if missing_files:
                report_lines.append(
                    "### Missing files (consider adding)\n",
                )
                report_lines.extend(f"{line}\n" for line in missing_files)
                report_lines.append("\n")
            if out_of_scope_items:
                report_lines.append(
                    "### Open problems (out of scope for this section)\n",
                )
                report_lines.extend(f"{line}\n" for line in out_of_scope_items)
                report_lines.append("\n")

    if has_feedback:
        feedback_report.write_text("".join(report_lines))
        print(f"[FEEDBACK] Scan feedback written to: {feedback_report}")
    else:
        report_lines.append("## No feedback\n")
        report_lines.append(
            "All files confirmed relevant. No missing files detected.\n",
        )
        feedback_report.write_text("".join(report_lines))

    # Route out-of-scope findings into scope-delta artifacts
    _route_scope_deltas(
        section_files=section_files,
        artifacts_dir=artifacts_dir,
        scan_log_dir=scan_log_dir,
    )

    # Apply feedback (missing + irrelevant files)
    if has_feedback:
        _apply_feedback(
            section_files=section_files,
            codemap_path=codemap_path,
            codespace=codespace,
            artifacts_dir=artifacts_dir,
            scan_log_dir=scan_log_dir,
            model_policy=model_policy,
        )

    return has_feedback


# ------------------------------------------------------------------
# Feedback application (P10+P3)
# ------------------------------------------------------------------


def _apply_feedback(
    *,
    section_files: list[Path],
    codemap_path: Path,
    codespace: Path,
    artifacts_dir: Path,
    scan_log_dir: Path,
    model_policy: dict[str, str],
) -> None:
    """Apply missing files and prune irrelevant files from feedback."""
    print("--- Deep Scan: applying feedback (missing + irrelevant files) ---")

    _paths = PathRegistry(artifacts_dir.parent)
    corrections_path = _paths.corrections()
    corrections_ref = ""
    if corrections_path.is_file():
        corrections_ref = (
            f"\n3. Codemap corrections (authoritative fixes): "
            f"`{corrections_path}`"
        )

    for section_file in section_files:
        sec_name = section_file.stem
        sec_log_dir = scan_log_dir / sec_name
        section_text = section_file.read_text()

        all_missing: list[str] = []
        all_irrelevant: list[str] = []

        for fb_file in sorted(sec_log_dir.glob("deep-*-feedback.json")):
            data = read_json(fb_file)
            if data is None:
                print(
                    f"[FEEDBACK][WARN] Malformed feedback JSON in "
                    f"apply_feedback: {fb_file}",
                )
                continue

            # Skip entries with missing required fields
            if not isinstance(data.get("relevant"), bool):
                continue
            if not isinstance(data.get("source_file"), str):
                continue

            # Collect missing
            for mf in data.get("missing_files", []):
                if isinstance(mf, str) and mf.strip():
                    all_missing.append(mf.strip())

            # Collect irrelevant
            if data["relevant"] is False:
                irr_path = data["source_file"]
                if irr_path:
                    all_irrelevant.append(irr_path)

        # Filter missing to those not already in the section
        truly_missing = [
            mf for mf in all_missing if f"### {mf}" not in section_text
        ]

        # Filter irrelevant to those actually in the section
        truly_irrelevant = [
            irf for irf in all_irrelevant if f"### {irf}" in section_text
        ]

        if not truly_missing and not truly_irrelevant:
            continue

        print(
            f"[FEEDBACK] {sec_name}: {len(truly_missing)} missing, "
            f"{len(truly_irrelevant)} irrelevant",
        )

        # Dispatch updater agent
        updater_prompt = sec_log_dir / "related-files-updater-prompt.md"
        updater_output = sec_log_dir / "related-files-updater-output.md"
        updater_signal = _paths.scan_related_files_update_signal(sec_name)

        missing_section = ""
        if truly_missing:
            items = "\n".join(f"- {mf}" for mf in truly_missing)
            missing_section = (
                f"## Missing Files Discovered by Deep Scan\n{items}\n\n"
            )

        irrelevant_section = ""
        if truly_irrelevant:
            items = "\n".join(f"- {irf}" for irf in truly_irrelevant)
            irrelevant_section = (
                f"## Irrelevant Files Identified by Deep Scan\n{items}\n\n"
                "These files were judged irrelevant to this section's "
                "concern by deep scan.\nOnly include them in removals if "
                "you agree they are unrelated to the\nsection's problem "
                "frame. Give a short reason for each removal.\n\n"
            )

        prompt = load_scan_template("related_files_updater.md").format(
            section_name=sec_name,
            section_file=section_file,
            codemap_path=codemap_path,
            corrections_ref=corrections_ref,
            missing_section=missing_section,
            irrelevant_section=irrelevant_section,
            updater_signal=updater_signal,
        )
        violations = validate_dynamic_content(prompt)
        if violations:
            print(
                f"[FEEDBACK] {sec_name}: updater prompt blocked — "
                f"safety violations: {violations}",
            )
            continue
        updater_prompt.write_text(prompt)

        updater_model = model_policy["feedback_updater"]
        escalation_model = model_policy["exploration"]
        result = dispatch_agent(
            model=updater_model,
            project=codespace,
            prompt_file=updater_prompt,
            agent_file=agent_for("scan.adjudicate"),
            stdout_file=updater_output,
        )

        # Check if signal is valid; escalate on failure
        if result.returncode == 0 and updater_signal.is_file():
            valid_signal = _is_valid_updater_signal(updater_signal)
        else:
            valid_signal = False

        if not valid_signal and result.returncode == 0:
            print(
                f"[FEEDBACK] {sec_name}: {updater_model} updater produced "
                f"no valid signal — escalating to {escalation_model}",
            )
            result = dispatch_agent(
                model=escalation_model,
                project=codespace,
                prompt_file=updater_prompt,
                agent_file=agent_for("scan.adjudicate"),
                stdout_file=updater_output,
            )
            valid_signal = (
                result.returncode == 0
                and updater_signal.is_file()
                and _is_valid_updater_signal(updater_signal)
            )

        if not valid_signal:
            if result.returncode != 0:
                _append_to_log(
                    scan_log_dir / "failures.log",
                    f"- Updater failed for {sec_name} (no valid signal "
                    "after escalation)",
                )
            continue

        sig_data = read_json(updater_signal)
        if sig_data is None:
            print(
                f"[FEEDBACK][WARN] Malformed updater signal: "
                f"{updater_signal} — preserved as .malformed.json",
            )
            continue
        status = sig_data.get("status", "")

        if status == "stale":
            applied = apply_related_files_update(
                section_file, updater_signal)
            # Acknowledge the signal — update status so it isn't
            # re-applied on subsequent runs.
            try:
                sig_data["status"] = "applied" if applied else "no_change"
                write_json(updater_signal, sig_data)
            except OSError:
                pass  # Best-effort ack; signal file may be read-only
            if applied:
                print(
                    f"[FEEDBACK] {sec_name}: related files updated "
                    "from deep scan feedback",
                )
